---
# tasks file for database
 - include_tasks: install_db.yml
 - include_tasks: start_mysql.yml
 - include_tasks: set_pswd.yml
 - include_tasks: create_db.yml
 - include_tasks: copy_script.yml
 - include_tasks: rundb_script.yml
